[package]
name = "imtrand"
version = "0.1.0"
edition = "2021"

[dependencies]

axum = { version = "0.8", features = ["http1", "json", "tokio", "tower-log", "tracing"], default-features = false }
tokio = { version = "1.51", features = ["macros", "rt-multi-thread"] }
imageproc = { version = "0.26" }
resvg = { version = "0.45", features = ["memmap-fonts", "system-fonts", "text"], default-features = false }
axum_typed_multipart = { version = "0.16.5", features = ["tempfile_3"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
