name: Build container

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: build-image
        run: |
         pack build imtrand -b paketo-community/rust -B paketobuildpacks/builder-jammy-base:latest
         docker image tag imtrand ghcr.io/simonerm/imtrand:next
         docker image push ghcr.io/simonerm/imtrand:next